"""Capabilities manifest -- what the LLM can call, in what tier.

The MCP server exposes this as a tool so the LLM can plan multi-step
answers. Without it, the LLM hallucinates tools that don't exist and
calls return 'tool not found' errors.

Two tiers:
  PRIMARY    -- standard physics, default-foregrounded
  EXTENDED   -- SSBM theoretical layer, only invoked on explicit request

See memory/project_mcp_server_positioning.md for the positioning rationale.
"""

from __future__ import annotations

from sigma_ground.mcp.provenance import ToolResult


_PRIMARY_TOOLS = [
    {
        "name": "lookup_constant",
        "tier": "PRIMARY",
        "domain": "constants",
        "summary": "Look up a physical constant by name. Tries sigma_ground curated, then scipy.constants CODATA.",
        "inputs": {"name": "str (e.g. 'G', 'speed_of_light', 'electron_mass')"},
        "returns": "value + units + source + uncertainty + provenance_tag",
    },
    {
        "name": "list_constants",
        "tier": "PRIMARY",
        "domain": "constants",
        "summary": "List constants available, with optional filter.",
        "inputs": {"category": "str|None: 'sigma_ground'|'codata'|'all'",
                    "contains": "str|None: substring filter",
                    "limit": "int (default 50)"},
        "returns": "list of constant names",
    },
    {
        "name": "convert_units",
        "tier": "PRIMARY",
        "domain": "units",
        "summary": "Convert a value between unit systems via pint.",
        "inputs": {"value": "float", "from_units": "str", "to_units": "str"},
        "returns": "converted value + target units",
    },
    {
        "name": "parse_quantity",
        "tier": "PRIMARY",
        "domain": "units",
        "summary": "Parse '5.6 light_years' into magnitude + units.",
        "inputs": {"quantity_string": "str"},
        "returns": "magnitude + units",
    },
    {
        "name": "solve_equation",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic solve via sympy. Accepts 'expr=0' or 'lhs=rhs'.",
        "inputs": {"equation": "str", "variable": "str"},
        "returns": "list of symbolic solutions",
    },
    {
        "name": "integrate_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic integration. Definite if bounds given.",
        "inputs": {"expression": "str", "variable": "str",
                    "lower": "str|None", "upper": "str|None"},
        "returns": "symbolic result",
    },
    {
        "name": "differentiate_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic differentiation.",
        "inputs": {"expression": "str", "variable": "str", "order": "int"},
        "returns": "symbolic derivative",
    },
    {
        "name": "simplify_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Apply sympy.simplify.",
        "inputs": {"expression": "str"},
        "returns": "simplified form",
    },
    {
        "name": "schwarzschild_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Schwarzschild radius r_s = 2 G M / c^2 in meters.",
        "inputs": {"mass_kg": "float (mass in kg)"},
        "returns": "r_s in meters",
    },
    {
        "name": "isco_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Innermost stable circular orbit r_ISCO = 6 G M / c^2.",
        "inputs": {"mass_kg": "float"},
        "returns": "r_ISCO in meters",
    },
    {
        "name": "photon_sphere_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Photon sphere r_ph = 3 G M / c^2.",
        "inputs": {"mass_kg": "float"},
        "returns": "r_ph in meters",
    },
    {
        "name": "hawking_temperature",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Hawking temperature T_H = hbar c^3 / (8 pi G M k_B) in K.",
        "inputs": {"mass_kg": "float"},
        "returns": "T_H in kelvin",
    },
    {
        "name": "hawking_evaporation_time",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Black-hole evaporation timescale in seconds.",
        "inputs": {"mass_kg": "float"},
        "returns": "tau in seconds",
    },
    {
        "name": "gravitational_redshift",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Schwarzschild gravitational redshift factor at radius r.",
        "inputs": {"mass_kg": "float", "radius_m": "float"},
        "returns": "z = (lambda_obs / lambda_emit) - 1",
    },
    {
        "name": "gravitational_time_dilation",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Clock-rate factor at radius r relative to infinity.",
        "inputs": {"mass_kg": "float", "radius_m": "float"},
        "returns": "dt_r / dt_inf = sqrt(1 - r_s/r)",
    },
    # ── kinematics (Phase 1.1) ──
    {"name": "free_fall_time", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Time to fall from rest: t=sqrt(2h/g) (vacuum).",
     "inputs": {"height_m": "float", "g_m_s2": "float (default 9.80665)"},
     "returns": "time in seconds"},
    {"name": "free_fall_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Impact speed: v=sqrt(2gh).",
     "inputs": {"height_m": "float", "g_m_s2": "float"},
     "returns": "velocity in m/s"},
    {"name": "projectile_range", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Range R = v^2 sin(2 theta)/g.",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "range in meters"},
    {"name": "projectile_max_height", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Max height (v sin theta)^2/(2g).",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "height in meters"},
    {"name": "projectile_flight_time", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Flight time 2 v sin(theta)/g.",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "time in seconds"},
    {"name": "kinetic_energy", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "KE = 0.5 m v^2 (non-relativistic).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "energy in joules"},
    {"name": "momentum", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "p = m v (non-relativistic).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "momentum in kg m/s"},
    {"name": "gravitational_potential_energy", "tier": "PRIMARY",
     "domain": "kinematics", "summary": "U = m g h (uniform gravity).",
     "inputs": {"mass_kg": "float", "height_m": "float", "g_m_s2": "float"},
     "returns": "energy in joules"},
    {"name": "friction_stopping_distance", "tier": "PRIMARY",
     "domain": "kinematics", "summary": "d = v^2 / (2 mu g).",
     "inputs": {"mass_kg": "float", "initial_velocity_m_s": "float",
                "friction_coefficient": "float", "g_m_s2": "float"},
     "returns": "distance in meters"},
    {"name": "circular_orbit_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Keplerian v = sqrt(G M / r).",
     "inputs": {"central_mass_kg": "float", "radius_m": "float"},
     "returns": "velocity in m/s"},
    {"name": "escape_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "v_esc = sqrt(2 G M / r).",
     "inputs": {"mass_kg": "float", "radius_m": "float"},
     "returns": "velocity in m/s"},
    # ── energy conversion (Phase 1.2) ──
    {"name": "mass_to_energy", "tier": "PRIMARY", "domain": "energy",
     "summary": "E = m c^2.",
     "inputs": {"mass_kg": "float"}, "returns": "energy in joules"},
    {"name": "energy_to_mass", "tier": "PRIMARY", "domain": "energy",
     "summary": "m = E / c^2.",
     "inputs": {"energy_j": "float"}, "returns": "mass in kg"},
    {"name": "luminosity_to_mass_conversion_rate", "tier": "PRIMARY",
     "domain": "energy", "summary": "dm/dt = L / c^2.",
     "inputs": {"luminosity_watts": "float"}, "returns": "kg/s"},
    {"name": "joules_to_eV", "tier": "PRIMARY", "domain": "energy",
     "summary": "Joule -> eV.",
     "inputs": {"energy_joules": "float"}, "returns": "energy in eV"},
    {"name": "eV_to_joules", "tier": "PRIMARY", "domain": "energy",
     "summary": "eV -> Joule.",
     "inputs": {"energy_eV": "float"}, "returns": "energy in joules"},
    {"name": "joules_to_TNT", "tier": "PRIMARY", "domain": "energy",
     "summary": "Joule -> tons/kt/MT TNT equivalent.",
     "inputs": {"energy_joules": "float", "unit": "str (ton/kt/MT)"},
     "returns": "tons TNT"},
    # ── special relativity (Phase 1.3) ──
    {"name": "lorentz_factor", "tier": "PRIMARY", "domain": "relativity",
     "summary": "gamma = 1/sqrt(1 - v^2/c^2).",
     "inputs": {"velocity_m_s": "float"}, "returns": "gamma (dimensionless)"},
    {"name": "relativistic_time_dilation", "tier": "PRIMARY",
     "domain": "relativity", "summary": "t = gamma t0.",
     "inputs": {"rest_time_s": "float", "velocity_m_s": "float"},
     "returns": "time in s"},
    {"name": "relativistic_length_contraction", "tier": "PRIMARY",
     "domain": "relativity", "summary": "L = L0 / gamma.",
     "inputs": {"rest_length_m": "float", "velocity_m_s": "float"},
     "returns": "length in m"},
    {"name": "relativistic_energy", "tier": "PRIMARY", "domain": "relativity",
     "summary": "E = gamma m c^2 (total).",
     "inputs": {"rest_mass_kg": "float", "velocity_m_s": "float"},
     "returns": "energy in joules"},
    {"name": "relativistic_momentum", "tier": "PRIMARY", "domain": "relativity",
     "summary": "p = gamma m v.",
     "inputs": {"rest_mass_kg": "float", "velocity_m_s": "float"},
     "returns": "kg m/s"},
    {"name": "relativistic_velocity_addition", "tier": "PRIMARY",
     "domain": "relativity", "summary": "(u+v)/(1+uv/c^2).",
     "inputs": {"u_m_s": "float", "v_m_s": "float"},
     "returns": "velocity in m/s"},
    {"name": "doppler_shift_factor", "tier": "PRIMARY", "domain": "relativity",
     "summary": "Relativistic Doppler factor.",
     "inputs": {"velocity_m_s": "float", "angle_to_los_deg": "float"},
     "returns": "lambda_obs/lambda_emit"},
    # ── cosmology (Phase 1.4) ──
    {"name": "hubble_radius", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "R_H = c / H_0.", "inputs": {}, "returns": "radius in meters"},
    {"name": "hde_dark_energy_density", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "HDE rho_DE; defaults c^2=DESI Union3 fit, L=R_H.",
     "inputs": {"c_squared": "float|None", "L_meters": "float|None"},
     "returns": "energy density in J/m^3"},
    {"name": "eta_desi_band_check", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Check adopted HDE c^2 within DESI Union3 1-sigma band.",
     "inputs": {"dataset": "str (dr2 or dr3)"}, "returns": "dict"},
    {"name": "mond_regime_classifier", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Classify accel as newtonian/transition/mond.",
     "inputs": {"acceleration_m_s2": "float"}, "returns": "regime label"},
    {"name": "mond_a0_constant", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Milgrom a_0 ~1.2e-10 m/s^2.", "inputs": {},
     "returns": "a_0 in m/s^2"},
    {"name": "critical_density", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "rho_crit = 3 H_0^2/(8 pi G).", "inputs": {},
     "returns": "density in kg/m^3"},
    {"name": "age_of_universe", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Hubble time t_H = 1/H_0.", "inputs": {},
     "returns": "time in seconds"},
    {"name": "eta_value_report", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Adopted HDE c^2 = DESI Union3 fit ~0.4122.", "inputs": {},
     "returns": "dimensionless"},
    # ── thermodynamics (Phase 1.5) ──
    {"name": "ideal_gas_pressure", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "P = n R T / V.",
     "inputs": {"n_moles": "float", "temperature_k": "float",
                "volume_m3": "float"}, "returns": "pressure in Pa"},
    {"name": "ideal_gas_volume", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "V = n R T / P.",
     "inputs": {"n_moles": "float", "temperature_k": "float",
                "pressure_pa": "float"}, "returns": "volume in m^3"},
    {"name": "blackbody_peak_wavelength", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "Wien lambda_max = b/T.",
     "inputs": {"temperature_k": "float"}, "returns": "wavelength in meters"},
    {"name": "blackbody_total_power", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "Stefan-Boltzmann P = sigma A T^4.",
     "inputs": {"temperature_k": "float", "area_m2": "float",
                "emissivity": "float"}, "returns": "power in watts"},
    {"name": "carnot_efficiency", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "eta = 1 - T_cold/T_hot.",
     "inputs": {"t_hot_k": "float", "t_cold_k": "float"},
     "returns": "dimensionless"},
    {"name": "thermal_energy_per_molecule", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "E = (f/2) k_B T.",
     "inputs": {"temperature_k": "float", "degrees_of_freedom": "int"},
     "returns": "energy in joules"},
    {"name": "speed_of_sound_in_ideal_gas", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "v = sqrt(gamma R T / M).",
     "inputs": {"temperature_k": "float", "gamma": "float",
                "molar_mass_kg_per_mol": "float"}, "returns": "speed in m/s"},
    {"name": "maxwell_boltzmann_most_probable_speed", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "v_p = sqrt(2 k_B T / m).",
     "inputs": {"temperature_k": "float", "molecular_mass_kg": "float"},
     "returns": "speed in m/s"},
    {"name": "temperature_celsius_to_kelvin", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "T_K = T_C + 273.15.",
     "inputs": {"t_celsius": "float"}, "returns": "temperature in K"},
    {"name": "temperature_kelvin_to_celsius", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "T_C = T_K - 273.15.",
     "inputs": {"t_kelvin": "float"}, "returns": "temperature in C"},
    # ── optics (Phase 1.6) ──
    {"name": "snells_law_refraction_angle", "tier": "PRIMARY",
     "domain": "optics", "summary": "n1 sin(theta1) = n2 sin(theta2).",
     "inputs": {"n1": "float", "n2": "float", "incident_angle_deg": "float"},
     "returns": "refracted angle in deg"},
    {"name": "critical_angle_for_tir", "tier": "PRIMARY", "domain": "optics",
     "summary": "Critical angle for TIR.",
     "inputs": {"n_dense": "float", "n_rare": "float"},
     "returns": "angle in deg"},
    {"name": "thin_lens_focal_length", "tier": "PRIMARY", "domain": "optics",
     "summary": "1/f = 1/d_o + 1/d_i.",
     "inputs": {"object_distance_m": "float", "image_distance_m": "float"},
     "returns": "f in meters"},
    {"name": "thin_lens_image_distance", "tier": "PRIMARY", "domain": "optics",
     "summary": "1/d_i = 1/f - 1/d_o.",
     "inputs": {"object_distance_m": "float", "focal_length_m": "float"},
     "returns": "d_i in meters"},
    {"name": "lens_magnification", "tier": "PRIMARY", "domain": "optics",
     "summary": "m = -d_i / d_o.",
     "inputs": {"object_distance_m": "float", "image_distance_m": "float"},
     "returns": "dimensionless"},
    {"name": "rydberg_hydrogen_wavelength", "tier": "PRIMARY", "domain": "optics",
     "summary": "Rydberg formula for hydrogen lines.",
     "inputs": {"n_initial": "int", "n_final": "int"},
     "returns": "wavelength in meters"},
    {"name": "double_slit_fringe_spacing", "tier": "PRIMARY", "domain": "optics",
     "summary": "y = lambda L / d.",
     "inputs": {"wavelength_m": "float", "slit_separation_m": "float",
                "screen_distance_m": "float"}, "returns": "fringe spacing m"},
    {"name": "single_slit_first_minimum_angle", "tier": "PRIMARY",
     "domain": "optics", "summary": "sin(theta) = lambda / a.",
     "inputs": {"wavelength_m": "float", "slit_width_m": "float"},
     "returns": "angle in deg"},
    {"name": "diffraction_grating_angle", "tier": "PRIMARY", "domain": "optics",
     "summary": "d sin(theta) = m lambda.",
     "inputs": {"wavelength_m": "float", "grating_spacing_m": "float",
                "order": "int"}, "returns": "angle in deg"},
    # ── materials (Phase 1.7) ──
    {"name": "density", "tier": "PRIMARY", "domain": "materials",
     "summary": "Material density in kg/m^3 (lookup).",
     "inputs": {"material": "str"}, "returns": "density in kg/m^3"},
    {"name": "refractive_index", "tier": "PRIMARY", "domain": "materials",
     "summary": "Refractive index at 589 nm (lookup).",
     "inputs": {"material": "str"}, "returns": "dimensionless n"},
    {"name": "melting_point", "tier": "PRIMARY", "domain": "materials",
     "summary": "Melting point in K (lookup).",
     "inputs": {"material": "str"}, "returns": "temperature in K"},
    {"name": "boiling_point", "tier": "PRIMARY", "domain": "materials",
     "summary": "Boiling point in K (lookup).",
     "inputs": {"material": "str"}, "returns": "temperature in K"},
    {"name": "youngs_modulus", "tier": "PRIMARY", "domain": "materials",
     "summary": "Young's modulus in Pa (lookup).",
     "inputs": {"material": "str"}, "returns": "Pa"},
    {"name": "band_gap_ev", "tier": "PRIMARY", "domain": "materials",
     "summary": "Semiconductor band gap in eV (lookup).",
     "inputs": {"material": "str"}, "returns": "eV"},
    {"name": "list_materials", "tier": "PRIMARY", "domain": "materials",
     "summary": "Inventory of materials in lookup tables.",
     "inputs": {}, "returns": "dict of available materials"},
    {"name": "element_atomic_data", "tier": "PRIMARY", "domain": "materials",
     "summary": "Element Z, name, mass via periodictable.",
     "inputs": {"element_symbol": "str"}, "returns": "dict"},
    # ── circuits (Phase 1.8) ──
    {"name": "ohms_law_voltage", "tier": "PRIMARY", "domain": "circuits",
     "summary": "V = I R.",
     "inputs": {"current_a": "float", "resistance_ohm": "float"},
     "returns": "voltage in V"},
    {"name": "ohms_law_current", "tier": "PRIMARY", "domain": "circuits",
     "summary": "I = V / R.",
     "inputs": {"voltage_v": "float", "resistance_ohm": "float"},
     "returns": "current in A"},
    {"name": "electrical_power", "tier": "PRIMARY", "domain": "circuits",
     "summary": "P = V I.",
     "inputs": {"voltage_v": "float", "current_a": "float"},
     "returns": "power in W"},
    {"name": "power_dissipation_resistor", "tier": "PRIMARY",
     "domain": "circuits", "summary": "P = I^2 R.",
     "inputs": {"current_a": "float", "resistance_ohm": "float"},
     "returns": "power in W"},
    {"name": "parallel_plate_capacitance", "tier": "PRIMARY", "domain": "circuits",
     "summary": "C = eps_0 eps_r A / d.",
     "inputs": {"area_m2": "float", "separation_m": "float",
                "dielectric_constant": "float"}, "returns": "C in farads"},
    {"name": "rc_time_constant", "tier": "PRIMARY", "domain": "circuits",
     "summary": "tau = R C.",
     "inputs": {"resistance_ohm": "float", "capacitance_f": "float"},
     "returns": "tau in seconds"},
    {"name": "rl_time_constant", "tier": "PRIMARY", "domain": "circuits",
     "summary": "tau = L / R.",
     "inputs": {"resistance_ohm": "float", "inductance_h": "float"},
     "returns": "tau in seconds"},
    {"name": "rlc_resonant_frequency", "tier": "PRIMARY", "domain": "circuits",
     "summary": "omega_0 = 1 / sqrt(L C).",
     "inputs": {"inductance_h": "float", "capacitance_f": "float"},
     "returns": "rad/s"},
    {"name": "em_wave_wavelength", "tier": "PRIMARY", "domain": "circuits",
     "summary": "lambda = c / (n f).",
     "inputs": {"frequency_hz": "float", "refractive_index": "float"},
     "returns": "wavelength in m"},
    {"name": "em_wave_frequency", "tier": "PRIMARY", "domain": "circuits",
     "summary": "f = c / (n lambda).",
     "inputs": {"wavelength_m": "float", "refractive_index": "float"},
     "returns": "frequency in Hz"},
    # ── atomic physics (Phase 1.9) ──
    # (element_atomic_data is registered under domain=materials; it
    # uses the periodictable library and covers all elements.)
    {"name": "first_ionization_energy", "tier": "PRIMARY", "domain": "atomic",
     "summary": "First IE in eV (NIST lookup).",
     "inputs": {"element_symbol": "str"}, "returns": "eV"},
    {"name": "hydrogen_like_energy_level", "tier": "PRIMARY", "domain": "atomic",
     "summary": "E_n = -13.606 Z^2/n^2 eV.",
     "inputs": {"n": "int", "atomic_number": "int"}, "returns": "eV"},
    {"name": "hydrogen_emission_wavelength", "tier": "PRIMARY",
     "domain": "atomic", "summary": "Rydberg transition wavelength.",
     "inputs": {"n_initial": "int", "n_final": "int",
                "atomic_number": "int"}, "returns": "wavelength in meters"},
    {"name": "de_broglie_wavelength", "tier": "PRIMARY", "domain": "atomic",
     "summary": "lambda = h / (m v).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "wavelength in m"},
    {"name": "photon_energy_from_wavelength", "tier": "PRIMARY",
     "domain": "atomic", "summary": "E = h c / lambda.",
     "inputs": {"wavelength_m": "float"}, "returns": "energy in joules"},
    {"name": "photon_energy_from_frequency", "tier": "PRIMARY",
     "domain": "atomic", "summary": "E = h f.",
     "inputs": {"frequency_hz": "float"}, "returns": "energy in joules"},
    # ── astronomy (Phase 1.10) ──
    {"name": "solar_system_body", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "Look up planet/moon/sun parameters.",
     "inputs": {"body_name": "str"}, "returns": "dict of parameters"},
    {"name": "named_star", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "Named bright star data (Sirius, Vega...).",
     "inputs": {"star_name": "str"}, "returns": "dict of parameters"},
    {"name": "light_travel_time", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "t = d / c.",
     "inputs": {"distance_m": "float"}, "returns": "seconds"},
    {"name": "list_bodies", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "List all solar-system bodies and named stars available.",
     "inputs": {}, "returns": "dict"},

    # ── orbital mechanics (body-aware, multi-step) ──
    {"name": "orbital_velocity", "tier": "PRIMARY", "domain": "orbital",
     "summary": "Circular orbital speed, body-aware: name + altitude_km (or "
                "radius_m, or semimajor_axis_au). Does mass lookup internally.",
     "inputs": {"central_body": "str (e.g. 'earth','sun')",
                "altitude_km": "float (above surface)",
                "orbital_radius_m": "float (from center)",
                "semimajor_axis_au": "float (heliocentric)"},
     "returns": "v in m/s"},
    {"name": "orbital_period", "tier": "PRIMARY", "domain": "orbital",
     "summary": "Kepler's third law T=2π√(a³/GM). Defaults to Sun. "
                "Asteroid at 3 AU: orbital_period(semimajor_axis_au=3).",
     "inputs": {"semimajor_axis_au": "float",
                "central_body": "str (default 'sun')"},
     "returns": "period in seconds"},
    {"name": "gravitational_force", "tier": "PRIMARY", "domain": "orbital",
     "summary": "Newton's law of gravitation F = G m1 m2 / r².",
     "inputs": {"mass1_kg": "float", "mass2_kg": "float",
                "separation_m": "float"}, "returns": "force in N"},
    {"name": "orbital_raise_energy", "tier": "PRIMARY", "domain": "orbital",
     "summary": "Gravitational PE to raise a mass between orbits ΔU=GMm(1/r1-1/r2). "
                "Body-aware (altitudes above surface).",
     "inputs": {"mass_kg": "float", "central_body": "str (default 'earth')",
                "from_altitude_km": "float", "to_altitude_km": "float"},
     "returns": "energy in J"},

    # ── nuclear physics ──
    {"name": "nuclear_binding_energy", "tier": "PRIMARY", "domain": "nuclear",
     "summary": "Binding energy + mass defect for a nucleus. Exact with "
                "measured_mass_u, else SEMF. Returns mass_defect_fraction "
                "(baryon-count vs mass-energy gap, peaks ~0.9% at iron).",
     "inputs": {"protons": "int", "neutrons": "int",
                "measured_mass_u": "float|None"},
     "returns": "dict {binding_energy_MeV, binding_per_nucleon_MeV, "
                "mass_defect_u, mass_defect_fraction}"},
    {"name": "coulomb_force", "tier": "PRIMARY", "domain": "nuclear",
     "summary": "Coulomb's law F = q1 q2 / (4π ε0 r²). +repulsive/−attractive.",
     "inputs": {"charge1_c": "float", "charge2_c": "float",
                "separation_m": "float"}, "returns": "force in N"},

    # ── multi-step atomic / circuits ──
    {"name": "de_broglie_from_kinetic_energy", "tier": "PRIMARY",
     "domain": "atomic",
     "summary": "de Broglie wavelength from KINETIC ENERGY (relativistically "
                "exact). '1 keV electron' = de_broglie_from_kinetic_energy("
                "1000,'electron').",
     "inputs": {"kinetic_energy_eV": "float",
                "particle": "str: electron|proton|neutron|alpha|muon"},
     "returns": "wavelength in m"},
    {"name": "energy_power_time", "tier": "PRIMARY", "domain": "circuits",
     "summary": "Solve E=P·t for the missing one; provide exactly two. "
                "'5 kW for 1 hr' = energy_power_time(power_w=5000,time_s=3600).",
     "inputs": {"power_w": "float|None", "time_s": "float|None",
                "energy_j": "float|None"}, "returns": "the missing quantity"},

    # ── procedures: canonical multi-step scientific routines ──
    {"name": "procedure_black_hole_profile", "tier": "PRIMARY", "domain": "procedures",
     "summary": "Full black-hole thermodynamics cascade from one mass: "
                "Schwarzschild radius → Hawking temperature → Bekenstein-Hawking "
                "entropy → evaporation time.",
     "inputs": {"mass_kg": "float"},
     "returns": "dict {steps[], result, summary}"},
    {"name": "procedure_photon_spectrum", "tier": "PRIMARY", "domain": "procedures",
     "summary": "Full photon cascade from one wavelength: frequency → energy "
                "(J and eV) → momentum.",
     "inputs": {"wavelength_m": "float"},
     "returns": "dict {steps[], result, summary}"},
    {"name": "procedure_relativistic_particle", "tier": "PRIMARY", "domain": "procedures",
     "summary": "Relativistic cascade: KE → Lorentz γ → total energy → momentum "
                "→ de Broglie wavelength.",
     "inputs": {"kinetic_energy_eV": "float",
                "particle": "str: electron|proton|neutron|muon"},
     "returns": "dict {steps[], result, summary}"},
    {"name": "procedure_projectile_trajectory", "tier": "PRIMARY", "domain": "procedures",
     "summary": "Projectile cascade (no drag): time of flight → range → max height.",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float"},
     "returns": "dict {steps[], result, summary}"},
    {"name": "procedure_stellar_blackbody", "tier": "PRIMARY", "domain": "procedures",
     "summary": "Blackbody cascade: Wien peak wavelength → Stefan-Boltzmann "
                "surface flux → peak photon energy.",
     "inputs": {"temperature_k": "float"},
     "returns": "dict {steps[], result, summary}"},

    # ── simulation: the Materia time-evolution engine ──
    {"name": "simulate", "tier": "PRIMARY", "domain": "simulation",
     "summary": "Natural-language physics what-if through the Materia simulator "
                "(falling, drag, terminal velocity, impact speed, reentry "
                "heating, parachute, projectile apex). Returns a worked answer "
                "or a clarification (value null) — never a fabricated number.",
     "inputs": {"scenario": "str (a plain-English what-if)"},
     "returns": "dict {value, units, notes, inputs.chain}"},
    {"name": "run_simulation", "tier": "PRIMARY", "domain": "simulation",
     "summary": "Run one Materia verb directly with explicit params "
                "(deterministic, no LLM). See list_simulation_scenarios.",
     "inputs": {"verb": "str", "params": "dict"},
     "returns": "dict {value, units, inputs.chain}"},
    {"name": "list_simulation_scenarios", "tier": "PRIMARY", "domain": "simulation",
     "summary": "List Materia simulation verbs with their input slots and "
                "named outputs.",
     "inputs": {}, "returns": "dict of verbs"},

    # ── chemistry: bonds, reactions, acids/bases, electrochem, solutions ──
    {"name": "bond_energy", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Bond dissociation energy (kJ/mol) for a diatomic bond.",
     "inputs": {"atom_a": "str", "atom_b": "str"}, "returns": "kJ/mol"},
    {"name": "bond_angle", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "VSEPR bond angle (deg) from steric number; bond_angle(4,0)=109.5°.",
     "inputs": {"electron_domains": "int", "lone_pairs": "int"},
     "returns": "degrees"},
    {"name": "reaction_enthalpy", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Standard reaction enthalpy ΔH° (kJ/mol) from formation enthalpies.",
     "inputs": {"reaction_key": "str (e.g. 'methane_combustion')"},
     "returns": "kJ/mol"},
    {"name": "weak_acid_ph", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "pH of a weak acid from its Ka; weak_acid_ph('acetic_acid',0.1)≈2.88.",
     "inputs": {"acid_key": "str", "concentration_mol_l": "float"},
     "returns": "pH"},
    {"name": "buffer_ph", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Buffer pH (Henderson-Hasselbalch): pH = pKa + log([base]/[acid]).",
     "inputs": {"acid_key": "str", "ratio_base_over_acid": "float"},
     "returns": "pH"},
    {"name": "cell_potential", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Galvanic cell EMF (V), Nernst-corrected; "
                "cell_potential('copper','zinc')≈1.10 V (Daniell).",
     "inputs": {"cathode": "str", "anode": "str", "reaction_quotient": "float"},
     "returns": "volts"},
    {"name": "electrolysis_mass", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Mass deposited by electrolysis (kg) — Faraday: m = M·I·t/(n·F).",
     "inputs": {"molar_mass_kg": "float", "current_a": "float",
                "time_s": "float", "electrons": "int"}, "returns": "kg"},
    {"name": "boiling_point_elevation", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Boiling-point elevation ΔTb (K) = i·Kb·molality (colligative).",
     "inputs": {"molality_mol_kg": "float", "van_t_hoff_i": "float"},
     "returns": "K"},
    {"name": "freezing_point_depression", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Freezing-point depression ΔTf (K) = i·Kf·molality (colligative).",
     "inputs": {"molality_mol_kg": "float", "van_t_hoff_i": "float"},
     "returns": "K"},
    {"name": "osmotic_pressure", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Osmotic pressure π (Pa) = i·M·R·T (van't Hoff).",
     "inputs": {"molarity_mol_l": "float", "van_t_hoff_i": "float"},
     "returns": "Pa"},
    {"name": "molar_solubility", "tier": "PRIMARY", "domain": "chemistry",
     "summary": "Molar solubility (mol/L) of a sparingly-soluble salt from Ksp.",
     "inputs": {"salt_key": "str (e.g. 'silver_chloride')"}, "returns": "mol/L"},

    # ── electronics: transport, semiconductors, junctions, capacitance ──
    {"name": "electrical_resistivity", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Electrical resistivity (Ω·m) of a metal; copper≈1.68e-8.",
     "inputs": {"metal_key": "str", "temperature_k": "float"}, "returns": "Ω·m"},
    {"name": "carrier_mobility", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Electron drift mobility (m²/V·s) of a metal (metals only).",
     "inputs": {"metal_key": "str", "temperature_k": "float"},
     "returns": "m²/V·s"},
    {"name": "hall_coefficient", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Hall coefficient (m³/C) of a metal: R_H = −1/(n·e).",
     "inputs": {"metal_key": "str"}, "returns": "m³/C"},
    {"name": "electron_mean_free_path", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Electron mean free path (m) in a metal; copper≈39 nm.",
     "inputs": {"metal_key": "str", "temperature_k": "float"}, "returns": "m"},
    {"name": "free_electron_density", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Free-electron (conduction) number density (m⁻³) of a metal.",
     "inputs": {"metal_key": "str"}, "returns": "m⁻³"},
    {"name": "semiconductor_band_gap", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Temperature-dependent band gap (eV) of a semiconductor "
                "(Varshni); silicon≈1.12 eV at 300 K.",
     "inputs": {"semiconductor_key": "str", "temperature_k": "float"},
     "returns": "eV"},
    {"name": "intrinsic_carrier_density", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Intrinsic carrier density n_i (m⁻³) of a semiconductor.",
     "inputs": {"semiconductor_key": "str", "temperature_k": "float"},
     "returns": "m⁻³"},
    {"name": "pn_built_in_voltage", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Built-in voltage of a p-n junction (V): "
                "V_bi = (kT/e) ln(N_A N_D / n_i²).",
     "inputs": {"semiconductor_key": "str", "donor_density_m3": "float",
                "acceptor_density_m3": "float", "temperature_k": "float"},
     "returns": "volts"},
    {"name": "depletion_width", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Depletion-region width of a p-n junction (m).",
     "inputs": {"semiconductor_key": "str", "donor_density_m3": "float",
                "acceptor_density_m3": "float", "applied_voltage_v": "float",
                "temperature_k": "float"}, "returns": "m"},
    {"name": "diode_current", "tier": "PRIMARY", "domain": "electronics",
     "summary": "Shockley diode current (A): I = I₀(exp(eV/kT) − 1).",
     "inputs": {"saturation_current_a": "float", "voltage_v": "float",
                "temperature_k": "float"}, "returns": "amperes"},
    # parallel_plate_capacitance is already published by the circuits group
    # (same physics, C = ε₀ε_r A / d) — not duplicated under electronics.

    # ── extended math (sympy): linear algebra, transforms, calculus ──
    {"name": "matrix_determinant", "tier": "PRIMARY", "domain": "math",
     "summary": "Determinant of a square matrix; '[[1,2],[3,4]]' -> -2.",
     "inputs": {"matrix": "str (nested-list, e.g. '[[1,2],[3,4]]')"},
     "returns": "determinant (str)"},
    {"name": "matrix_eigenvalues", "tier": "PRIMARY", "domain": "math",
     "summary": "Eigenvalues of a square matrix (with multiplicity).",
     "inputs": {"matrix": "str (nested-list)"}, "returns": "list of eigenvalues"},
    {"name": "matrix_inverse", "tier": "PRIMARY", "domain": "math",
     "summary": "Inverse of a square matrix.",
     "inputs": {"matrix": "str (nested-list)"}, "returns": "inverse matrix (str)"},
    {"name": "matrix_multiply", "tier": "PRIMARY", "domain": "math",
     "summary": "Matrix product A*B.",
     "inputs": {"matrix_a": "str", "matrix_b": "str"}, "returns": "product (str)"},
    {"name": "solve_linear_system", "tier": "PRIMARY", "domain": "math",
     "summary": "Solve A x = b; matrix_a='[[2,1],[1,3]]', vector_b='[1,2]'.",
     "inputs": {"matrix_a": "str", "vector_b": "str"},
     "returns": "solution vector"},
    {"name": "compute_limit", "tier": "PRIMARY", "domain": "math",
     "summary": "Limit of expression as variable->point; 'sin(x)/x' -> 1.",
     "inputs": {"expression": "str", "variable": "str", "point": "str",
                "direction": "str '+'|'-'|'+-'"}, "returns": "limit (str)"},
    {"name": "series_expansion", "tier": "PRIMARY", "domain": "math",
     "summary": "Taylor/Maclaurin series about a point to a given order.",
     "inputs": {"expression": "str", "variable": "str", "point": "str",
                "order": "int"}, "returns": "series (str)"},
    {"name": "summation", "tier": "PRIMARY", "domain": "math",
     "summary": "Symbolic sum over a variable; '1/n**2' to oo -> pi**2/6.",
     "inputs": {"expression": "str", "variable": "str", "lower": "str",
                "upper": "str ('oo'=infinity)"}, "returns": "sum (str)"},
    {"name": "laplace_transform", "tier": "PRIMARY", "domain": "math",
     "summary": "Laplace transform F(s)=L{f(t)}; 'exp(-2*t)' -> 1/(s+2).",
     "inputs": {"expression": "str", "t_var": "str", "s_var": "str"},
     "returns": "F(s) (str)"},
    {"name": "fourier_transform", "tier": "PRIMARY", "domain": "math",
     "summary": "Fourier transform of an expression.",
     "inputs": {"expression": "str", "x_var": "str", "k_var": "str"},
     "returns": "F(k) (str)"},
    {"name": "factor_expression", "tier": "PRIMARY", "domain": "math",
     "summary": "Factor a polynomial/expression; 'x**2-1' -> (x-1)(x+1).",
     "inputs": {"expression": "str"}, "returns": "factored form (str)"},
    {"name": "expand_expression", "tier": "PRIMARY", "domain": "math",
     "summary": "Expand an expression; '(x+1)**2' -> x**2+2*x+1.",
     "inputs": {"expression": "str"}, "returns": "expanded form (str)"},
    {"name": "solve_ode", "tier": "PRIMARY", "domain": "math",
     "summary": "Solve an ODE (use y, y', y''); \"y''+y\" -> C1*sin(x)+C2*cos(x).",
     "inputs": {"equation": "str", "func": "str", "variable": "str"},
     "returns": "general solution (str)"},
    {"name": "gradient", "tier": "PRIMARY", "domain": "math",
     "summary": "Gradient grad(f) of a scalar field.",
     "inputs": {"scalar_field": "str", "variables": "str (comma-separated)"},
     "returns": "gradient components"},
    {"name": "divergence", "tier": "PRIMARY", "domain": "math",
     "summary": "Divergence div(F) of a vector field.",
     "inputs": {"vector_field": "str (comma-separated)", "variables": "str"},
     "returns": "divergence (str)"},
    {"name": "curl", "tier": "PRIMARY", "domain": "math",
     "summary": "Curl of a 3-component vector field; '-y,x,0' -> [0,0,2].",
     "inputs": {"vector_field": "str (3 comps)", "variables": "str"},
     "returns": "curl components"},
    {"name": "percent_of", "tier": "PRIMARY", "domain": "math",
     "summary": "X percent of a value: (percent/100)*value; (2,60) -> 1.2.",
     "inputs": {"percent": "float", "value": "float"}, "returns": "result"},

    # ── frontier physics (standard: BH thermo, Unruh, entanglement) ──
    {"name": "bekenstein_hawking_entropy", "tier": "PRIMARY", "domain": "frontier",
     "summary": "Black-hole entropy/temperature/horizon-area/r_s from mass; "
                "solar mass entropy ~1e77 k_B.",
     "inputs": {"mass_kg": "float"},
     "returns": "dict {entropy_k_B, horizon_area_m2, schwarzschild_radius_m, "
                "hawking_temperature_K}"},
    {"name": "gravitational_binding_energy", "tier": "PRIMARY", "domain": "frontier",
     "summary": "Self-gravity binding energy of a uniform sphere U=(3/5)GM^2/R; "
                "Earth ~2.24e32 J.",
     "inputs": {"mass_kg": "float", "radius_m": "float"},
     "returns": "energy in J"},
    {"name": "unruh_temperature", "tier": "PRIMARY", "domain": "frontier",
     "summary": "Unruh temperature of an accelerated observer T=hbar a/(2 pi c k_B).",
     "inputs": {"acceleration_m_s2": "float"}, "returns": "temperature in K"},
    {"name": "entanglement_channel", "tier": "PRIMARY", "domain": "frontier",
     "summary": "Whether entanglement can signal (NO, no-communication theorem), "
                "do QKD (shared secret key), and the CHSH/Tsirelson bound (2 sqrt2). "
                "Pass the user's question as scenario.",
     "inputs": {"scenario": "str (the question)"},
     "returns": "dict {verdict, primary, ...}"},

    # ── mechanics (composite analysis tools) ──
    {"name": "collision_analysis", "tier": "PRIMARY", "domain": "mechanics",
     "summary": "1D two-body collision: elastic velocities, inelastic outcome, KE lost.",
     "inputs": {"mass1_kg": "float", "velocity1_m_s": "float",
                "mass2_kg": "float", "velocity2_m_s": "float",
                "restitution": "float"}, "returns": "dict {velocities, energy_lost_J}"},
    {"name": "work_energy_analysis", "tier": "PRIMARY", "domain": "mechanics",
     "summary": "Work, power, friction loss, gravitational PE, rotational KE, "
                "impulse, total mechanical energy of a moving body.",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float", "height_m": "float",
                "force_n": "float", "distance_m": "float"},
     "returns": "dict of energies/power"},
    {"name": "projectile_analysis", "tier": "PRIMARY", "domain": "mechanics",
     "summary": "Projectile range/apex/flight-time (vacuum) + drag force, "
                "terminal velocity, drag-corrected range. angle in degrees.",
     "inputs": {"speed_m_s": "float", "angle_deg": "float", "mass_kg": "float",
                "drag_coefficient": "float", "area_m2": "float"},
     "returns": "dict {range_m, max_height_m, time_of_flight_s, ...}"},
    {"name": "incline_analysis", "tier": "PRIMARY", "domain": "mechanics",
     "summary": "Inclined plane: critical sliding angle, slide distance up, "
                "speed at the bottom. angle in degrees.",
     "inputs": {"angle_deg": "float", "friction_coefficient": "float",
                "speed_m_s": "float", "height_m": "float"},
     "returns": "dict {critical_angle, distance, speed}"},

    # ── transport & statistical mechanics (composite) ──
    {"name": "viscous_flow_analysis", "tier": "PRIMARY", "domain": "fluids",
     "summary": "Viscous flow: Reynolds number, Stokes drag + terminal velocity, "
                "drag coefficient, Poiseuille pipe flow, boundary layer, wall shear.",
     "inputs": {"velocity_m_s": "float", "radius_m": "float",
                "viscosity_pa_s": "float", "fluid_density_kg_m3": "float"},
     "returns": "dict of flow quantities"},
    {"name": "diffusion_analysis", "tier": "PRIMARY", "domain": "fluids",
     "summary": "Diffusion: Einstein-Stokes diffusivity, Fick's first & second "
                "laws, penetration time, Darken interdiffusion.",
     "inputs": {"temperature_k": "float", "diffusivity_m2_s": "float"},
     "returns": "dict of diffusion quantities"},
    {"name": "statistical_distribution", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "Fermi-Dirac & Bose-Einstein occupation, partition function, "
                "mean energy, entropy, equipartition heat capacity.",
     "inputs": {"temperature_k": "float", "energy_ev": "float"},
     "returns": "dict of distribution quantities"},
    {"name": "rotational_dynamics", "tier": "PRIMARY", "domain": "mechanics",
     "summary": "Moment of inertia (rod + shape geometry), parallel-axis, "
                "angular momentum, torque, angular acceleration, rolling ramp.",
     "inputs": {"mass_kg": "float", "radius_m": "float", "angle_deg": "float",
                "angular_velocity_rad_s": "float"},
     "returns": "dict of rotational quantities"},
    {"name": "atomic_angular_momentum", "tier": "PRIMARY", "domain": "quantum",
     "summary": "|J| magnitude, allowed m_j, spin-orbit coupling energy/"
                "splitting, Lande interval (L=2, S=1/2).",
     "inputs": {"total_j": "float", "spin_orbit_constant_ev": "float"},
     "returns": "dict of angular-momentum quantities"},
    {"name": "elastic_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Elastic response: uniaxial/shear/hydrostatic stress, strain-"
                "energy densities, transverse strain, volume change, von Mises yield.",
     "inputs": {"material_key": "str (e.g. 'iron','copper','aluminum','steel_mild')",
                "strain": "float"}, "returns": "dict of stresses/energies"},
    {"name": "stress_failure_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Fracture/fatigue/creep: stress-intensity, critical crack "
                "length, fatigue life, Paris life, creep rate + rupture time.",
     "inputs": {"material_key": "str", "applied_stress": "float (Pa)"},
     "returns": "dict of fracture/fatigue/creep quantities"},
    {"name": "plasticity_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Plastic flow stress: Johnson-Cook, Ludwik hardening, work-"
                "hardening rate.",
     "inputs": {"material_key": "str", "plastic_strain": "float"},
     "returns": "dict of flow stresses"},
    {"name": "composite_bounds_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Two-phase composite bounds: Voigt-Reuss-Hill, Hashin-Shtrikman, "
                "thermal-conductivity bounds, Gibson-Ashby foam strength.",
     "inputs": {"bulk_modulus1_pa": "float", "bulk_modulus2_pa": "float",
                "fraction1": "float"}, "returns": "dict of composite bounds"},
    {"name": "optical_waveguide_analysis", "tier": "PRIMARY", "domain": "photonics",
     "summary": "Slab dielectric waveguide: numerical aperture, V-number "
                "(normalized frequency), guided TE-mode count.",
     "inputs": {"wavelength_m": "float", "core_thickness_m": "float",
                "n_core": "float", "n_clad": "float"},
     "returns": "dict of waveguide quantities"},
    {"name": "photonic_bandgap_analysis", "tier": "PRIMARY", "domain": "photonics",
     "summary": "Quarter-wave Bragg mirror / 1D photonic bandgap: center "
                "wavelength, stop-band fractional width, peak reflectance.",
     "inputs": {"design_wavelength_m": "float", "n_low": "float",
                "n_high": "float", "n_pairs": "int"},
     "returns": "dict of Bragg-stack quantities"},
    {"name": "nonlinear_optics_analysis", "tier": "PRIMARY", "domain": "photonics",
     "summary": "Nonlinear optics: Kerr index, B-integral (nonlinear phase), "
                "self-focusing critical power, SHG efficiency factor.",
     "inputs": {"intensity_w_m2": "float", "wavelength_m": "float",
                "n0": "float", "n2_m2_w": "float", "length_m": "float"},
     "returns": "dict of nonlinear-optics quantities"},
    {"name": "material_color_analysis", "tier": "PRIMARY", "domain": "optics",
     "summary": "Physically-derived sRGB color of a material (metal Drude "
                "reflectance, organic spectrum, or dye-on-substrate).",
     "inputs": {"category": "str ('metal'/'organic'/'dye')", "key": "str (e.g. 'gold')"},
     "returns": "dict with rgb_0_1, rgb_8bit, hex"},
    {"name": "phosphor_decay_analysis", "tier": "PRIMARY", "domain": "optics",
     "summary": "Phosphor / luminescence afterglow brightness "
                "I(t)=I0 exp(-t/tau) and surviving fraction at time t.",
     "inputs": {"time_s": "float", "tau_s": "float", "initial_brightness": "float"},
     "returns": "dict with brightness, fraction_remaining"},
    {"name": "piezoelectric_actuator_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Converse piezoelectric effect: induced strain (d E) and tip "
                "displacement (d E L) of an actuator under applied field.",
     "inputs": {"material_key": "str (quartz/PZT4/PZT5A/BaTiO3/LiNbO3/AlN/PVDF)",
                "e_field_v_m": "float", "length_m": "float"},
     "returns": "dict with strain, displacement_m"},
    {"name": "dielectric_polarization_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Relative permittivity from the Clausius-Mossotti relation "
                "given molecular polarizability and number density.",
     "inputs": {"polarizability_fm2": "float", "number_density_m3": "float"},
     "returns": "dict with relative_permittivity"},
    {"name": "thermoelectric_generator_analysis", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "Thermoelectric generator: Carnot limit, Seebeck thermocouple "
                "voltage, leg resistance, max power, ZT efficiency, heat flow.",
     "inputs": {"hot_temperature_k": "float", "cold_temperature_k": "float",
                "material_key": "str", "mat_p": "str", "mat_n": "str"},
     "returns": "dict of TEG quantities"},
    {"name": "natural_convection_analysis", "tier": "PRIMARY", "domain": "fluids",
     "summary": "Buoyancy-driven natural convection of a gas: buoyancy velocity, "
                "Grashof number (laminar/turbulent), binary gas diffusivity.",
     "inputs": {"hot_temperature_k": "float", "ambient_temperature_k": "float",
                "length_m": "float", "gas_key": "str (N2/O2/CO2/H2O/CH4/CO)"},
     "returns": "dict with buoyancy velocity, Grashof, diffusivity"},
    {"name": "viscoelastic_creep_analysis", "tier": "PRIMARY", "domain": "materials",
     "summary": "Viscoelastic creep & relaxation: Maxwell, Kelvin-Voigt, "
                "standard-linear-solid creep, and SLS stress relaxation.",
     "inputs": {"material_key": "str", "time_s": "float", "applied_stress": "float (Pa)",
                "temperature_k": "float"},
     "returns": "dict of strains and relaxed stress"},
    {"name": "acoustic_interface_analysis", "tier": "PRIMARY", "domain": "acoustics",
     "summary": "Sound at a planar interface: energy reflection/transmission "
                "coefficients, Snell refraction angle, critical angle (TIR).",
     "inputs": {"material_key_1": "str", "material_key_2": "str",
                "incidence_angle_deg": "float"},
     "returns": "dict of acoustic-interface quantities"},
    {"name": "capacitor_analysis", "tier": "PRIMARY", "domain": "electromagnetism",
     "summary": "Capacitance of parallel-plate, coaxial, and concentric-sphere "
                "geometries, plus energy stored on the parallel-plate cap.",
     "inputs": {"area_m2": "float", "separation_m": "float", "epsilon_r": "float",
                "voltage_v": "float"},
     "returns": "dict of capacitances and stored energy"},
    {"name": "hall_effect_analysis", "tier": "PRIMARY", "domain": "electromagnetism",
     "summary": "Hall voltage of a current-carrying conductor in a transverse "
                "magnetic field (negative for electron carriers).",
     "inputs": {"material_key": "str", "current_a": "float", "b_field_t": "float",
                "thickness_m": "float"},
     "returns": "dict with hall_voltage_V"},
    {"name": "semiconductor_junction_analysis", "tier": "PRIMARY", "domain": "electronics",
     "summary": "p-n junction: depletion (junction) capacitance and reverse "
                "saturation current.",
     "inputs": {"sc_key": "str (silicon/germanium/gallium_arsenide/...)",
                "donor_density": "float", "acceptor_density": "float", "area_m2": "float"},
     "returns": "dict with junction_capacitance_F, saturation_current_A"},
    {"name": "superconducting_gap_analysis", "tier": "PRIMARY", "domain": "condensed_matter",
     "summary": "BCS spectroscopic gap frequency f=2*Delta/h from the critical "
                "temperature (Delta = 1.764 k_B Tc).",
     "inputs": {"critical_temp_k": "float"},
     "returns": "dict with gap_frequency_Hz"},
    {"name": "quantum_tunneling_analysis", "tier": "PRIMARY", "domain": "quantum",
     "summary": "WKB transmission probability through a rectangular potential "
                "barrier.",
     "inputs": {"barrier_height_eV": "float", "particle_energy_eV": "float",
                "barrier_width_nm": "float"},
     "returns": "dict with transmission_probability"},
    {"name": "quantum_box_energy_analysis", "tier": "PRIMARY", "domain": "quantum",
     "summary": "Energy of a state (n1,n2,n3) for a particle in a 3D cubic "
                "infinite well.",
     "inputs": {"n1": "int", "n2": "int", "n3": "int", "box_size_nm": "float"},
     "returns": "dict with energy_eV"},
    {"name": "band_dos_shape_analysis", "tier": "PRIMARY", "domain": "condensed_matter",
     "summary": "Tight-binding density-of-states shape factor at the Fermi level "
                "for a transition metal (van Hove peak > 1, pseudogap < 1).",
     "inputs": {"structure": "str (bcc/fcc/hcp)", "d_electron_count": "int (1-9)"},
     "returns": "dict with dos_shape_factor"},
    {"name": "magnetic_exchange_analysis", "tier": "PRIMARY", "domain": "condensed_matter",
     "summary": "Two-site Heisenberg model for a magnetic ion: exchange J from "
                "crystal field, VQE vs exact ground energy, spin state.",
     "inputs": {"atomic_number": "int", "oxidation_state": "int",
                "coord_key": "str (e.g. 'oxide_oct')"},
     "returns": "dict of exchange/VQE quantities"},
]


_EXTENDED_TOOLS: list[dict] = [
    # SSBM-specific tools will be wired here later. They exist in the
    # sigma_ground library already (entanglement.py, sigma-page-time,
    # sigma-bounds) but are deliberately not foregrounded in PRIMARY.
    # See memory/project_mcp_server_positioning.md.
]


# Merge keyword/formula/attribution metadata from the sidecar.
# This adds a `keywords` list to each tool dict so the MCP capability
# manifest publishes the formal names ('Schwarzschild radius',
# 'Stefan-Boltzmann law', 'Hawking 1974') alongside the canonical
# tool names. The benchmark TOOL INDEX surfaces them so the LLM can
# match 'event horizon of the Sun' -> schwarzschild_radius.
try:
    from sigma_ground.mcp.tool_keywords import TOOL_KEYWORDS as _TK
    for _t in _PRIMARY_TOOLS:
        _t["keywords"] = _TK.get(_t["name"], [])
except ImportError:
    for _t in _PRIMARY_TOOLS:
        _t.setdefault("keywords", [])


def get_manifest() -> ToolResult:
    """Return the full capabilities manifest.

    The LLM calls this first to know what tools exist. Without it,
    function-calling regimes will hallucinate tools.

    Returns
    -------
    ToolResult whose `value` is a dict with 'primary' and 'extended'
    tool listings.
    """
    return ToolResult(
        value={
            "primary": _PRIMARY_TOOLS,
            "extended": _EXTENDED_TOOLS,
            "positioning": (
                "PRIMARY tier is standard physics with rigorous provenance. "
                "Foreground these for routine queries. EXTENDED tier is the "
                "SSBM (Scale-Shifted Baryonic Matter) theoretical layer; "
                "invoke only when the user explicitly asks about black hole "
                "interior structure, cosmic-origin-as-BH hypothesis, sigma-"
                "field dynamics, or wants to compare standard physics to an "
                "alternative theoretical framework. Do NOT volunteer SSBM "
                "framing for ordinary physics questions."
            ),
            "response_style": (
                "Every answer should faithfully report the `source` and "
                "`provenance_tag` from each ToolResult, in addition to the "
                "value and units. This is the tool's distinguishing feature "
                "vs other physics assistants -- transparent provenance."
            ),
        },
        source="sigma_ground.mcp.manifest",
        notes=(
            f"{len(_PRIMARY_TOOLS)} primary tool(s), "
            f"{len(_EXTENDED_TOOLS)} extended tool(s). "
            "Use lookup_constant() or domain-specific tools by name. "
            "Pass inputs as the field types listed."
        ),
    )
