"""Capabilities manifest -- what the LLM can call, in what tier.

The MCP server exposes this as a tool so the LLM can plan multi-step
answers. Without it, the LLM hallucinates tools that don't exist and
calls return 'tool not found' errors.

Two tiers:
  PRIMARY    -- standard physics, default-foregrounded
  EXTENDED   -- SSBM theoretical layer, only invoked on explicit request

See memory/project_mcp_server_positioning.md for the positioning rationale.
"""

from __future__ import annotations

from sigma_ground.mcp.provenance import ToolResult


_PRIMARY_TOOLS = [
    {
        "name": "lookup_constant",
        "tier": "PRIMARY",
        "domain": "constants",
        "summary": "Look up a physical constant by name. Tries sigma_ground curated, then scipy.constants CODATA.",
        "inputs": {"name": "str (e.g. 'G', 'speed_of_light', 'electron_mass')"},
        "returns": "value + units + source + uncertainty + provenance_tag",
    },
    {
        "name": "list_constants",
        "tier": "PRIMARY",
        "domain": "constants",
        "summary": "List constants available, with optional filter.",
        "inputs": {"category": "str|None: 'sigma_ground'|'codata'|'all'",
                    "contains": "str|None: substring filter",
                    "limit": "int (default 50)"},
        "returns": "list of constant names",
    },
    {
        "name": "convert_units",
        "tier": "PRIMARY",
        "domain": "units",
        "summary": "Convert a value between unit systems via pint.",
        "inputs": {"value": "float", "from_units": "str", "to_units": "str"},
        "returns": "converted value + target units",
    },
    {
        "name": "parse_quantity",
        "tier": "PRIMARY",
        "domain": "units",
        "summary": "Parse '5.6 light_years' into magnitude + units.",
        "inputs": {"quantity_string": "str"},
        "returns": "magnitude + units",
    },
    {
        "name": "solve_equation",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic solve via sympy. Accepts 'expr=0' or 'lhs=rhs'.",
        "inputs": {"equation": "str", "variable": "str"},
        "returns": "list of symbolic solutions",
    },
    {
        "name": "integrate_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic integration. Definite if bounds given.",
        "inputs": {"expression": "str", "variable": "str",
                    "lower": "str|None", "upper": "str|None"},
        "returns": "symbolic result",
    },
    {
        "name": "differentiate_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Symbolic differentiation.",
        "inputs": {"expression": "str", "variable": "str", "order": "int"},
        "returns": "symbolic derivative",
    },
    {
        "name": "simplify_expr",
        "tier": "PRIMARY",
        "domain": "symbolic",
        "summary": "Apply sympy.simplify.",
        "inputs": {"expression": "str"},
        "returns": "simplified form",
    },
    {
        "name": "schwarzschild_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Schwarzschild radius r_s = 2 G M / c^2 in meters.",
        "inputs": {"mass_kg": "float (mass in kg)"},
        "returns": "r_s in meters",
    },
    {
        "name": "isco_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Innermost stable circular orbit r_ISCO = 6 G M / c^2.",
        "inputs": {"mass_kg": "float"},
        "returns": "r_ISCO in meters",
    },
    {
        "name": "photon_sphere_radius",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Photon sphere r_ph = 3 G M / c^2.",
        "inputs": {"mass_kg": "float"},
        "returns": "r_ph in meters",
    },
    {
        "name": "hawking_temperature",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Hawking temperature T_H = hbar c^3 / (8 pi G M k_B) in K.",
        "inputs": {"mass_kg": "float"},
        "returns": "T_H in kelvin",
    },
    {
        "name": "hawking_evaporation_time",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Black-hole evaporation timescale in seconds.",
        "inputs": {"mass_kg": "float"},
        "returns": "tau in seconds",
    },
    {
        "name": "gravitational_redshift",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Schwarzschild gravitational redshift factor at radius r.",
        "inputs": {"mass_kg": "float", "radius_m": "float"},
        "returns": "z = (lambda_obs / lambda_emit) - 1",
    },
    {
        "name": "gravitational_time_dilation",
        "tier": "PRIMARY",
        "domain": "gr",
        "summary": "Clock-rate factor at radius r relative to infinity.",
        "inputs": {"mass_kg": "float", "radius_m": "float"},
        "returns": "dt_r / dt_inf = sqrt(1 - r_s/r)",
    },
    # ── kinematics (Phase 1.1) ──
    {"name": "free_fall_time", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Time to fall from rest: t=sqrt(2h/g) (vacuum).",
     "inputs": {"height_m": "float", "g_m_s2": "float (default 9.80665)"},
     "returns": "time in seconds"},
    {"name": "free_fall_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Impact speed: v=sqrt(2gh).",
     "inputs": {"height_m": "float", "g_m_s2": "float"},
     "returns": "velocity in m/s"},
    {"name": "projectile_range", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Range R = v^2 sin(2 theta)/g.",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "range in meters"},
    {"name": "projectile_max_height", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Max height (v sin theta)^2/(2g).",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "height in meters"},
    {"name": "projectile_flight_time", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Flight time 2 v sin(theta)/g.",
     "inputs": {"initial_speed_m_s": "float", "launch_angle_deg": "float",
                "g_m_s2": "float"},
     "returns": "time in seconds"},
    {"name": "kinetic_energy", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "KE = 0.5 m v^2 (non-relativistic).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "energy in joules"},
    {"name": "momentum", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "p = m v (non-relativistic).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "momentum in kg m/s"},
    {"name": "gravitational_potential_energy", "tier": "PRIMARY",
     "domain": "kinematics", "summary": "U = m g h (uniform gravity).",
     "inputs": {"mass_kg": "float", "height_m": "float", "g_m_s2": "float"},
     "returns": "energy in joules"},
    {"name": "friction_stopping_distance", "tier": "PRIMARY",
     "domain": "kinematics", "summary": "d = v^2 / (2 mu g).",
     "inputs": {"mass_kg": "float", "initial_velocity_m_s": "float",
                "friction_coefficient": "float", "g_m_s2": "float"},
     "returns": "distance in meters"},
    {"name": "circular_orbit_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "Keplerian v = sqrt(G M / r).",
     "inputs": {"central_mass_kg": "float", "radius_m": "float"},
     "returns": "velocity in m/s"},
    {"name": "escape_velocity", "tier": "PRIMARY", "domain": "kinematics",
     "summary": "v_esc = sqrt(2 G M / r).",
     "inputs": {"mass_kg": "float", "radius_m": "float"},
     "returns": "velocity in m/s"},
    # ── energy conversion (Phase 1.2) ──
    {"name": "mass_to_energy", "tier": "PRIMARY", "domain": "energy",
     "summary": "E = m c^2.",
     "inputs": {"mass_kg": "float"}, "returns": "energy in joules"},
    {"name": "energy_to_mass", "tier": "PRIMARY", "domain": "energy",
     "summary": "m = E / c^2.",
     "inputs": {"energy_j": "float"}, "returns": "mass in kg"},
    {"name": "luminosity_to_mass_conversion_rate", "tier": "PRIMARY",
     "domain": "energy", "summary": "dm/dt = L / c^2.",
     "inputs": {"luminosity_watts": "float"}, "returns": "kg/s"},
    {"name": "joules_to_eV", "tier": "PRIMARY", "domain": "energy",
     "summary": "Joule -> eV.",
     "inputs": {"energy_joules": "float"}, "returns": "energy in eV"},
    {"name": "eV_to_joules", "tier": "PRIMARY", "domain": "energy",
     "summary": "eV -> Joule.",
     "inputs": {"energy_eV": "float"}, "returns": "energy in joules"},
    {"name": "joules_to_TNT", "tier": "PRIMARY", "domain": "energy",
     "summary": "Joule -> tons/kt/MT TNT equivalent.",
     "inputs": {"energy_joules": "float", "unit": "str (ton/kt/MT)"},
     "returns": "tons TNT"},
    # ── special relativity (Phase 1.3) ──
    {"name": "lorentz_factor", "tier": "PRIMARY", "domain": "relativity",
     "summary": "gamma = 1/sqrt(1 - v^2/c^2).",
     "inputs": {"velocity_m_s": "float"}, "returns": "gamma (dimensionless)"},
    {"name": "relativistic_time_dilation", "tier": "PRIMARY",
     "domain": "relativity", "summary": "t = gamma t0.",
     "inputs": {"rest_time_s": "float", "velocity_m_s": "float"},
     "returns": "time in s"},
    {"name": "relativistic_length_contraction", "tier": "PRIMARY",
     "domain": "relativity", "summary": "L = L0 / gamma.",
     "inputs": {"rest_length_m": "float", "velocity_m_s": "float"},
     "returns": "length in m"},
    {"name": "relativistic_energy", "tier": "PRIMARY", "domain": "relativity",
     "summary": "E = gamma m c^2 (total).",
     "inputs": {"rest_mass_kg": "float", "velocity_m_s": "float"},
     "returns": "energy in joules"},
    {"name": "relativistic_momentum", "tier": "PRIMARY", "domain": "relativity",
     "summary": "p = gamma m v.",
     "inputs": {"rest_mass_kg": "float", "velocity_m_s": "float"},
     "returns": "kg m/s"},
    {"name": "relativistic_velocity_addition", "tier": "PRIMARY",
     "domain": "relativity", "summary": "(u+v)/(1+uv/c^2).",
     "inputs": {"u_m_s": "float", "v_m_s": "float"},
     "returns": "velocity in m/s"},
    {"name": "doppler_shift_factor", "tier": "PRIMARY", "domain": "relativity",
     "summary": "Relativistic Doppler factor.",
     "inputs": {"velocity_m_s": "float", "angle_to_los_deg": "float"},
     "returns": "lambda_obs/lambda_emit"},
    # ── cosmology (Phase 1.4) ──
    {"name": "hubble_radius", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "R_H = c / H_0.", "inputs": {}, "returns": "radius in meters"},
    {"name": "hde_dark_energy_density", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "HDE rho_DE; defaults c^2=ETA, L=R_H.",
     "inputs": {"c_squared": "float|None", "L_meters": "float|None"},
     "returns": "energy density in J/m^3"},
    {"name": "eta_desi_band_check", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Check ETA within DESI Union3 1-sigma band.",
     "inputs": {"dataset": "str (dr2 or dr3)"}, "returns": "dict"},
    {"name": "mond_regime_classifier", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Classify accel as newtonian/transition/mond.",
     "inputs": {"acceleration_m_s2": "float"}, "returns": "regime label"},
    {"name": "mond_a0_constant", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Milgrom a_0 ~1.2e-10 m/s^2.", "inputs": {},
     "returns": "a_0 in m/s^2"},
    {"name": "critical_density", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "rho_crit = 3 H_0^2/(8 pi G).", "inputs": {},
     "returns": "density in kg/m^3"},
    {"name": "age_of_universe", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "Hubble time t_H = 1/H_0.", "inputs": {},
     "returns": "time in seconds"},
    {"name": "eta_value_report", "tier": "PRIMARY", "domain": "cosmology",
     "summary": "ETA = c^2_DESI ~0.4122.", "inputs": {},
     "returns": "dimensionless"},
    # ── thermodynamics (Phase 1.5) ──
    {"name": "ideal_gas_pressure", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "P = n R T / V.",
     "inputs": {"n_moles": "float", "temperature_k": "float",
                "volume_m3": "float"}, "returns": "pressure in Pa"},
    {"name": "ideal_gas_volume", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "V = n R T / P.",
     "inputs": {"n_moles": "float", "temperature_k": "float",
                "pressure_pa": "float"}, "returns": "volume in m^3"},
    {"name": "blackbody_peak_wavelength", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "Wien lambda_max = b/T.",
     "inputs": {"temperature_k": "float"}, "returns": "wavelength in meters"},
    {"name": "blackbody_total_power", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "Stefan-Boltzmann P = sigma A T^4.",
     "inputs": {"temperature_k": "float", "area_m2": "float",
                "emissivity": "float"}, "returns": "power in watts"},
    {"name": "carnot_efficiency", "tier": "PRIMARY", "domain": "thermodynamics",
     "summary": "eta = 1 - T_cold/T_hot.",
     "inputs": {"t_hot_k": "float", "t_cold_k": "float"},
     "returns": "dimensionless"},
    {"name": "thermal_energy_per_molecule", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "E = (f/2) k_B T.",
     "inputs": {"temperature_k": "float", "degrees_of_freedom": "int"},
     "returns": "energy in joules"},
    {"name": "speed_of_sound_in_ideal_gas", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "v = sqrt(gamma R T / M).",
     "inputs": {"temperature_k": "float", "gamma": "float",
                "molar_mass_kg_per_mol": "float"}, "returns": "speed in m/s"},
    {"name": "maxwell_boltzmann_most_probable_speed", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "v_p = sqrt(2 k_B T / m).",
     "inputs": {"temperature_k": "float", "molecular_mass_kg": "float"},
     "returns": "speed in m/s"},
    {"name": "temperature_celsius_to_kelvin", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "T_K = T_C + 273.15.",
     "inputs": {"t_celsius": "float"}, "returns": "temperature in K"},
    {"name": "temperature_kelvin_to_celsius", "tier": "PRIMARY",
     "domain": "thermodynamics", "summary": "T_C = T_K - 273.15.",
     "inputs": {"t_kelvin": "float"}, "returns": "temperature in C"},
    # ── optics (Phase 1.6) ──
    {"name": "snells_law_refraction_angle", "tier": "PRIMARY",
     "domain": "optics", "summary": "n1 sin(theta1) = n2 sin(theta2).",
     "inputs": {"n1": "float", "n2": "float", "incident_angle_deg": "float"},
     "returns": "refracted angle in deg"},
    {"name": "critical_angle_for_tir", "tier": "PRIMARY", "domain": "optics",
     "summary": "Critical angle for TIR.",
     "inputs": {"n_dense": "float", "n_rare": "float"},
     "returns": "angle in deg"},
    {"name": "thin_lens_focal_length", "tier": "PRIMARY", "domain": "optics",
     "summary": "1/f = 1/d_o + 1/d_i.",
     "inputs": {"object_distance_m": "float", "image_distance_m": "float"},
     "returns": "f in meters"},
    {"name": "thin_lens_image_distance", "tier": "PRIMARY", "domain": "optics",
     "summary": "1/d_i = 1/f - 1/d_o.",
     "inputs": {"object_distance_m": "float", "focal_length_m": "float"},
     "returns": "d_i in meters"},
    {"name": "lens_magnification", "tier": "PRIMARY", "domain": "optics",
     "summary": "m = -d_i / d_o.",
     "inputs": {"object_distance_m": "float", "image_distance_m": "float"},
     "returns": "dimensionless"},
    {"name": "rydberg_hydrogen_wavelength", "tier": "PRIMARY", "domain": "optics",
     "summary": "Rydberg formula for hydrogen lines.",
     "inputs": {"n_initial": "int", "n_final": "int"},
     "returns": "wavelength in meters"},
    {"name": "double_slit_fringe_spacing", "tier": "PRIMARY", "domain": "optics",
     "summary": "y = lambda L / d.",
     "inputs": {"wavelength_m": "float", "slit_separation_m": "float",
                "screen_distance_m": "float"}, "returns": "fringe spacing m"},
    {"name": "single_slit_first_minimum_angle", "tier": "PRIMARY",
     "domain": "optics", "summary": "sin(theta) = lambda / a.",
     "inputs": {"wavelength_m": "float", "slit_width_m": "float"},
     "returns": "angle in deg"},
    {"name": "diffraction_grating_angle", "tier": "PRIMARY", "domain": "optics",
     "summary": "d sin(theta) = m lambda.",
     "inputs": {"wavelength_m": "float", "grating_spacing_m": "float",
                "order": "int"}, "returns": "angle in deg"},
    # ── materials (Phase 1.7) ──
    {"name": "density", "tier": "PRIMARY", "domain": "materials",
     "summary": "Material density in kg/m^3 (lookup).",
     "inputs": {"material": "str"}, "returns": "density in kg/m^3"},
    {"name": "refractive_index", "tier": "PRIMARY", "domain": "materials",
     "summary": "Refractive index at 589 nm (lookup).",
     "inputs": {"material": "str"}, "returns": "dimensionless n"},
    {"name": "melting_point", "tier": "PRIMARY", "domain": "materials",
     "summary": "Melting point in K (lookup).",
     "inputs": {"material": "str"}, "returns": "temperature in K"},
    {"name": "boiling_point", "tier": "PRIMARY", "domain": "materials",
     "summary": "Boiling point in K (lookup).",
     "inputs": {"material": "str"}, "returns": "temperature in K"},
    {"name": "youngs_modulus", "tier": "PRIMARY", "domain": "materials",
     "summary": "Young's modulus in Pa (lookup).",
     "inputs": {"material": "str"}, "returns": "Pa"},
    {"name": "band_gap_ev", "tier": "PRIMARY", "domain": "materials",
     "summary": "Semiconductor band gap in eV (lookup).",
     "inputs": {"material": "str"}, "returns": "eV"},
    {"name": "list_materials", "tier": "PRIMARY", "domain": "materials",
     "summary": "Inventory of materials in lookup tables.",
     "inputs": {}, "returns": "dict of available materials"},
    {"name": "element_atomic_data", "tier": "PRIMARY", "domain": "materials",
     "summary": "Element Z, name, mass via periodictable.",
     "inputs": {"element_symbol": "str"}, "returns": "dict"},
    # ── circuits (Phase 1.8) ──
    {"name": "ohms_law_voltage", "tier": "PRIMARY", "domain": "circuits",
     "summary": "V = I R.",
     "inputs": {"current_a": "float", "resistance_ohm": "float"},
     "returns": "voltage in V"},
    {"name": "ohms_law_current", "tier": "PRIMARY", "domain": "circuits",
     "summary": "I = V / R.",
     "inputs": {"voltage_v": "float", "resistance_ohm": "float"},
     "returns": "current in A"},
    {"name": "electrical_power", "tier": "PRIMARY", "domain": "circuits",
     "summary": "P = V I.",
     "inputs": {"voltage_v": "float", "current_a": "float"},
     "returns": "power in W"},
    {"name": "power_dissipation_resistor", "tier": "PRIMARY",
     "domain": "circuits", "summary": "P = I^2 R.",
     "inputs": {"current_a": "float", "resistance_ohm": "float"},
     "returns": "power in W"},
    {"name": "parallel_plate_capacitance", "tier": "PRIMARY", "domain": "circuits",
     "summary": "C = eps_0 eps_r A / d.",
     "inputs": {"area_m2": "float", "separation_m": "float",
                "dielectric_constant": "float"}, "returns": "C in farads"},
    {"name": "rc_time_constant", "tier": "PRIMARY", "domain": "circuits",
     "summary": "tau = R C.",
     "inputs": {"resistance_ohm": "float", "capacitance_f": "float"},
     "returns": "tau in seconds"},
    {"name": "rl_time_constant", "tier": "PRIMARY", "domain": "circuits",
     "summary": "tau = L / R.",
     "inputs": {"resistance_ohm": "float", "inductance_h": "float"},
     "returns": "tau in seconds"},
    {"name": "rlc_resonant_frequency", "tier": "PRIMARY", "domain": "circuits",
     "summary": "omega_0 = 1 / sqrt(L C).",
     "inputs": {"inductance_h": "float", "capacitance_f": "float"},
     "returns": "rad/s"},
    {"name": "em_wave_wavelength", "tier": "PRIMARY", "domain": "circuits",
     "summary": "lambda = c / (n f).",
     "inputs": {"frequency_hz": "float", "refractive_index": "float"},
     "returns": "wavelength in m"},
    {"name": "em_wave_frequency", "tier": "PRIMARY", "domain": "circuits",
     "summary": "f = c / (n lambda).",
     "inputs": {"wavelength_m": "float", "refractive_index": "float"},
     "returns": "frequency in Hz"},
    # ── atomic physics (Phase 1.9) ──
    {"name": "first_ionization_energy", "tier": "PRIMARY", "domain": "atomic",
     "summary": "First IE in eV (NIST lookup).",
     "inputs": {"element_symbol": "str"}, "returns": "eV"},
    {"name": "hydrogen_like_energy_level", "tier": "PRIMARY", "domain": "atomic",
     "summary": "E_n = -13.606 Z^2/n^2 eV.",
     "inputs": {"n": "int", "atomic_number": "int"}, "returns": "eV"},
    {"name": "hydrogen_emission_wavelength", "tier": "PRIMARY",
     "domain": "atomic", "summary": "Rydberg transition wavelength.",
     "inputs": {"n_initial": "int", "n_final": "int",
                "atomic_number": "int"}, "returns": "wavelength in meters"},
    {"name": "de_broglie_wavelength", "tier": "PRIMARY", "domain": "atomic",
     "summary": "lambda = h / (m v).",
     "inputs": {"mass_kg": "float", "velocity_m_s": "float"},
     "returns": "wavelength in m"},
    {"name": "photon_energy_from_wavelength", "tier": "PRIMARY",
     "domain": "atomic", "summary": "E = h c / lambda.",
     "inputs": {"wavelength_m": "float"}, "returns": "energy in joules"},
    {"name": "photon_energy_from_frequency", "tier": "PRIMARY",
     "domain": "atomic", "summary": "E = h f.",
     "inputs": {"frequency_hz": "float"}, "returns": "energy in joules"},
    # ── astronomy (Phase 1.10) ──
    {"name": "solar_system_body", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "Look up planet/moon/sun parameters.",
     "inputs": {"body_name": "str"}, "returns": "dict of parameters"},
    {"name": "named_star", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "Named bright star data (Sirius, Vega...).",
     "inputs": {"star_name": "str"}, "returns": "dict of parameters"},
    {"name": "light_travel_time", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "t = d / c.",
     "inputs": {"distance_m": "float"}, "returns": "seconds"},
    {"name": "list_bodies", "tier": "PRIMARY", "domain": "astronomy",
     "summary": "List all solar-system bodies and named stars available.",
     "inputs": {}, "returns": "dict"},
]


_EXTENDED_TOOLS: list[dict] = [
    # SSBM-specific tools will be wired here later. They exist in the
    # sigma_ground library already (entanglement.py, sigma-page-time,
    # sigma-bounds) but are deliberately not foregrounded in PRIMARY.
    # See memory/project_mcp_server_positioning.md.
]


def get_manifest() -> ToolResult:
    """Return the full capabilities manifest.

    The LLM calls this first to know what tools exist. Without it,
    function-calling regimes will hallucinate tools.

    Returns
    -------
    ToolResult whose `value` is a dict with 'primary' and 'extended'
    tool listings.
    """
    return ToolResult(
        value={
            "primary": _PRIMARY_TOOLS,
            "extended": _EXTENDED_TOOLS,
            "positioning": (
                "PRIMARY tier is standard physics with rigorous provenance. "
                "Foreground these for routine queries. EXTENDED tier is the "
                "SSBM (Scale-Shifted Baryonic Matter) theoretical layer; "
                "invoke only when the user explicitly asks about black hole "
                "interior structure, cosmic-origin-as-BH hypothesis, sigma-"
                "field dynamics, or wants to compare standard physics to an "
                "alternative theoretical framework. Do NOT volunteer SSBM "
                "framing for ordinary physics questions."
            ),
            "response_style": (
                "Every answer should faithfully report the `source` and "
                "`provenance_tag` from each ToolResult, in addition to the "
                "value and units. This is the tool's distinguishing feature "
                "vs other physics assistants -- transparent provenance."
            ),
        },
        source="sigma_ground.mcp.manifest",
        notes=(
            f"{len(_PRIMARY_TOOLS)} primary tool(s), "
            f"{len(_EXTENDED_TOOLS)} extended tool(s). "
            "Use lookup_constant() or domain-specific tools by name. "
            "Pass inputs as the field types listed."
        ),
    )
